version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - net_worth_tracker_DB__uri=postgresql://postgres:postgres@db:5432/net_worth_tracker
      - net_worth_tracker_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: net_worth_tracker_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/net_worth_tracker_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=net_worth_tracker, net_worth_tracker_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
